# Generated by Django 2.0.7 on 2019-07-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='filler',
            new_name='dummy',
        ),
    ]
