# Generated by Django 2.0.7 on 2019-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190712_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterModelTable(
            name='dummy',
            table='info',
        ),
    ]
